### ISSUE TITLE
Please select and add information about a license to the repository

### ISSUE THREAD

**Issue by it-praktyk** [ibotty/golang-github-prometheus-node_exporter#1]
Thank you for your work!

We used your work and added support for compiling package for CentOS 6 package too. 

Before we realase it to a community we need receive approvals from a legal department. For ask them we need to know what is the license for your code first.

More about licensing code in the repository you can find [here](https://help.github.com/articles/licensing-a-repository/) or [here](https://choosealicense.com/).

Thank you for your understanding.

**Comment by ibotty** [comment]
Sorry! I missed the issue. I don't think a rpm package is complex enough to warrant having to license it (in Germany its "Schöpfungshöhe"). But if others think otherwise, I hereby place it in the public domain. I will indicate it in the repo in a minute.

**Comment by ibotty** [comment]
Oh, and if you prefer a license, MIT is fine.

**Comment by ibotty** [comment]
Oh, I totally forgot: In Germany, I can't put something into the public domain. So MIT it is.

**Comment by it-praktyk** [comment]
Thank you!

**Comment by ibotty** [comment]
There has been a request for centos 6 packages: @it-praktyk: can you submit your changes (as a pull request)? That would be great!

**Comment by it-praktyk** [comment]
I've prepared the package as a part of my contract. Before I left the company what I did that work I started an internal procedure to contribute this part of my work to a Community.

Due to the signed contract, I can't share more information. Sorry.
