### ISSUE TITLE
CentOS 8 builds

### ISSUE THREAD

**Issue by breed808** [ibotty/golang-github-prometheus-node_exporter#10]
Hello,

Would it be possible to enable builds for CentOS 8 in the COPR repository?
I've been able to rebuild the package myself using `mock` as a workaround for now.

Many thanks for your work on packaging this exporter!

**Comment by ibotty** [comment]
I triggered a build of node-exporter 0.18 against centos8.

Unfortunately 1.0 does not build with older go compilers: prometheus/node_exporter#1704
I will track this problem (because it also affects Fedora <32) in #11.

**Comment by breed808** [comment]
Thanks for triggering the build!
