### ISSUE TITLE
CentOS 7 systemd: Failed at step USER spawning: No such process

### ISSUE THREAD

**Issue by mog01** [ibotty/golang-github-prometheus-node_exporter#14]
Hi,

I happened to notice node_exporter has been updated for CentOS 7 to version:

golang-github-prometheus-node-exporter-1.1.1-2.el7.x86_64

I thought I should try it out :)

However, when I enable it in systemctl and start it... It gives this error:

May 19 10:36:09 prometheus systemd: Started Node Exporter.
May 19 10:36:09 prometheus systemd: Failed at step USER spawning /usr/sbin/node_exporter: No such process
May 19 10:36:09 prometheus systemd: node_exporter.service: main process exited, code=exited, status=217/USER
May 19 10:36:09 prometheus systemd: Unit node_exporter.service entered failed state.
May 19 10:36:09 prometheus systemd: node_exporter.service failed.

Has anyone else noticed this please? Thanks in advance!

**Comment by ibotty** [comment]
Where did you find this package?  My recentish builds failed.

**Comment by mog01** [comment]
Found it from general YUM repo:

Installed Packages
Name        : golang-github-prometheus-node-exporter
Arch        : x86_64
Version     : 1.1.1
Release     : 2.el7
Size        : 17 M
Repo        : installed
From repo   : epel
Summary     : Exporter for machine metrics
URL         : https://github.com/prometheus/node_exporter
Licence     : ASL 2.0 and MIT
Description : 
            : Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written
            : in Go with pluggable metric collectors.

**Comment by ibotty** [comment]
Wow.  So it's part of EPEL7 now.  That's great.  The relevant bugtracker for it is https://bugzilla.redhat.com/buglist.cgi?component=golang-github-prometheus-node-exporter&list_id=11885917&product=Fedora
