### ISSUE TITLE
COPR repository package is out of date

### ISSUE THREAD

**Issue by godefroi** [ibotty/golang-github-prometheus-node_exporter#2]
The COPR repository package is currently at 0.14.0-5.fc26. Additionally, when run with `node_exporter -version`, the output is as follows:
```
node_exporter, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.6.3
```

**Comment by ibotty** [comment]
Oh, I did not get a notification that a new version is out! The new version just got build.

I don't know why the version is not shown. Can you file another bug report.

**Comment by ibotty** [comment]
The version is shown in the latest version.
