### ISSUE TITLE
Exporters for Red Hat and CentOS 6

### ISSUE THREAD

**Issue by finkr** [ibotty/golang-github-prometheus-node_exporter#3]
Hello,

We would like to use Prometheus to monitor ou servers, which also has some Red Hat and CentOS 6.

We wonder if you plan to add RHEL6 / CentOS 6 packages for client side exporter (especially  node_exporter, procfs, pushgateway...)

Thanks

**Comment by ibotty** [comment]
I can look into it. I'll have to check whether there are any centos 6 chroots on copr.

Can you try to build the package on centos manually and see if something fails?

**Comment by finkr** [comment]
Hello,

We have successfully compiled and tested node_exporter 0.15.0 with Go 1.10 on RHEL 6

Let me know if I can do something else,

Regards,

Franklin

**Comment by ibotty** [comment]
Can you share an init script?

**Comment by ibotty** [comment]
@finkr Can you check why the 0.17 build fails on centos 6?  I lack the motivation and time to fix up the build.

**Comment by dekimsey** [comment]
@ibotty If you can link me to a srpm, I can look into the build issue on CentOS 6. I'm not familiar with Copr, but I might be able to provide something helpful.

**Comment by finkr** [comment]
Closing since rhel6/centos6 aren't supported anymore.

**Comment by finkr** [comment]
Closing since rhel6/centos6 aren't supported anymore.
