### ISSUE TITLE
installing 0.15 version ?

### ISSUE THREAD

**Issue by jouve** [ibotty/golang-github-prometheus-node_exporter#4]
Hi,

looking here https://copr.fedorainfracloud.org/coprs/ibotty/prometheus-exporters/packages/ there is only 0.16 version of node_exporter.

Can you confirm it's the only available now ?

**Comment by ibotty** [comment]
I don't think copr stores old versions. I know that 0.16 includes some breaking changes (And I would have preferred they continue adding the old labels, at least for some releases). Do you absolutely need an old version? If so, I could version the rpms in the name (prometheus-exporter015 or similar). But I prefer not having to do that.

**Comment by jouve** [comment]
I asked in case I missed something. 

Thanks for the reply :)
